spring.application.name=Spring-Boot-With-Redis

spring.datasource.url=jdbc:postgresql://localhost:5432/user_management
spring.datasource.username=postgres
spring.datasource.password=postgres@123
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql = true


spring.redis.host=localhost
spring.redis.port=6379
#spring.redis.password=yourpassword